"""Deterministic offline builder for the ``sampled_frame_bundle`` artifact.

The pilot's ``sampled_frames`` representation is a JSON *description* of
sampled frames -- a few kilobytes of text produced by a vision model. This
module builds a different, additional representation carrying the actual JPEG
bytes those descriptions were written from. It does not replace, redefine, or
touch ``sampled_frames``.

What this can and cannot establish
----------------------------------
The JPEG bytes fed to the historical description model were never retained.
This builder can therefore show that regenerated frames come from the same
source video, at the same timestamps, with the same dimensions, frame count,
and declared encoder settings -- that is, that they are **aligned with the
frozen sampling metadata and algorithm**. It cannot and does not claim the
regenerated bytes are identical to the historical visual input, and every
manifest it writes says so in those words.

Determinism
-----------
Output is byte-identical for identical inputs and software. Tar members carry
explicit ``TarInfo`` metadata rather than whatever the filesystem happened to
report, JSON is canonical, and no generation timestamp enters any
checksum-covered file.
"""

from __future__ import annotations

import io
import json
import shutil
import tarfile
from dataclasses import dataclass
from hashlib import sha256
from importlib import metadata
from pathlib import Path
from tempfile import mkdtemp
from typing import Any, Callable, Iterable, Mapping, Protocol, Sequence

from .video_prep import SampledImage, sample_video


FRAME_BUNDLE_SCHEMA_VERSION = "pathfinder.sampled-frame-bundle/v0.1"
FRAME_BUNDLE_GENERATION_SCHEMA_VERSION = (
    "pathfinder.frame-bundle-generation/v0.1"
)
REPRESENTATION_ID = "sampled_frame_bundle"
#: The representation this bundle accompanies; deliberately left untouched.
SOURCE_REPRESENTATION_ID = "sampled_frames"
FRAME_DESCRIPTION_SCHEMA_VERSION = (
    "pathfinder.sampled-frame-observations/v1alpha1"
)
BUNDLE_NAME = "sampled_frame_bundle.tar"
OBJECT_MANIFEST_NAME = "frame_bundle_manifest.json"
GENERATION_MANIFEST_NAME = "frame-bundle-generation-manifest.json"
CHECKSUM_NAME = "SHA256SUMS"
FRAMES_DIRECTORY = "frames"
#: Encoder settings the existing sampler hard-codes. Recorded, not applied.
JPEG_QUALITY = 82
JPEG_OPTIMIZE = True
SAMPLING_METHOD = "uniform-midpoint"
#: Fixed tar member metadata. Anything derived from the filesystem would make
#: the archive depend on when and where it was built.
TAR_MTIME = 0
TAR_MODE = 0o644
TAR_FORMAT = tarfile.USTAR_FORMAT
_ALIGNMENT_STATEMENT = (
    "These JPEG frames were regenerated from the same source video using "
    "the same sampling algorithm and are aligned with the frozen sampling "
    "metadata: identical frame count, frame indices, timestamps, widths, "
    "heights, and declared encoder settings. The JPEG bytes supplied to the "
    "historical description model were not retained, so this artifact does "
    "NOT claim byte identity with the historical visual input."
)


class FrameBundleError(ValueError):
    """Raised when a bundle cannot be built from the frozen inputs."""


def _require(condition: object, message: str) -> None:
    if not condition:
        raise FrameBundleError(message)


def _canonical_json(value: Any) -> bytes:
    """One canonical serialisation, used everywhere bytes must match."""
    return (
        json.dumps(value, indent=2, sort_keys=True, ensure_ascii=False)
        + "\n"
    ).encode("utf-8")


def _sha256_bytes(payload: bytes) -> str:
    return sha256(payload).hexdigest()


def _sha256_file(path: Path) -> str:
    digest = sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1 << 20), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _contained(root: Path, candidate: str, label: str) -> Path:
    """Resolve a manifest-declared relative path inside its root.

    Manifest paths are data. A ``..`` segment or an absolute path would
    otherwise let a manifest read or write outside the directory the operator
    named.
    """
    _require(
        isinstance(candidate, str) and candidate.strip(),
        f"{label} must be a non-empty string",
    )
    raw = Path(candidate)
    _require(not raw.is_absolute(), f"{label} must be relative: {candidate}")
    _require(
        ".." not in raw.parts,
        f"{label} must not traverse upwards: {candidate}",
    )
    resolved = (root / raw).resolve()
    root_resolved = root.resolve()
    _require(
        resolved == root_resolved or root_resolved in resolved.parents,
        f"{label} escapes its declared root: {candidate}",
    )
    return resolved


class FrameSampler(Protocol):
    """The decoding boundary, injectable so packaging is testable."""

    def __call__(
        self,
        path: Path,
        *,
        frame_count: int,
        jpeg_max_dimension: int,
    ) -> tuple[list[SampledImage], float]:
        ...


@dataclass(frozen=True)
class FrozenObject:
    """One object's authoritative inputs, already validated."""

    object_id: str
    source_video_id: str
    video_filename: str
    video_size_bytes: int
    video_sha256: str
    video_path: Path
    frame_descriptions_relative_path: str
    frame_descriptions_sha256: str
    frame_count: int
    jpeg_max_dimension: int
    sampling_method: str
    source_duration_seconds: float
    frames: tuple[dict[str, Any], ...]


def _software_versions() -> dict[str, str | None]:
    """Versions relevant to decoding and encoding, recorded not asserted."""
    versions: dict[str, str | None] = {}
    for name in ("av", "Pillow", "pathfinder-minimal"):
        try:
            versions[name] = metadata.version(name)
        except metadata.PackageNotFoundError:
            versions[name] = None
    return versions


def _load_generation_manifest(
    representation_dir: Path,
    generation_manifest: Path | None,
) -> tuple[Path, dict[str, Any], bytes]:
    if generation_manifest is not None:
        path = Path(generation_manifest).resolve()
        _require(
            path.is_file(),
            f"generation manifest does not exist: {path}",
        )
    else:
        candidates = sorted(
            representation_dir.glob("generation-manifest.json")
        )
        _require(
            len(candidates) == 1,
            "the generation manifest could not be unambiguously discovered "
            f"in {representation_dir}; supply --generation-manifest",
        )
        path = candidates[0].resolve()
    raw = path.read_bytes()
    try:
        payload = json.loads(raw)
    except json.JSONDecodeError as exc:
        raise FrameBundleError(
            f"malformed generation manifest: {path}"
        ) from exc
    _require(
        isinstance(payload, Mapping),
        "the generation manifest must be an object",
    )
    return path, dict(payload), raw


def _validate_objects(
    manifest: Mapping[str, Any],
    *,
    representation_dir: Path,
    video_dir: Path,
) -> list[FrozenObject]:
    """Validate every declared object, failing closed on any disagreement."""
    entries = manifest.get("objects")
    _require(
        isinstance(entries, list) and entries,
        "the generation manifest declares no objects",
    )
    declared_frame_count = manifest.get("frame_count")
    declared_max_dimension = manifest.get("jpeg_max_dimension")
    _require(
        isinstance(declared_frame_count, int)
        and not isinstance(declared_frame_count, bool)
        and declared_frame_count > 0,
        "the generation manifest has no usable frame_count",
    )
    _require(
        isinstance(declared_max_dimension, int)
        and not isinstance(declared_max_dimension, bool)
        and declared_max_dimension > 0,
        "the generation manifest has no usable jpeg_max_dimension",
    )

    objects: list[FrozenObject] = []
    seen: set[str] = set()
    for index, entry in enumerate(entries):
        where = f"objects[{index}]"
        _require(isinstance(entry, Mapping), f"{where} must be an object")
        object_id = entry.get("object_id")
        _require(
            isinstance(object_id, str) and object_id.strip(),
            f"{where}.object_id must be a non-empty string",
        )
        object_id = object_id.strip()
        _require(
            object_id not in seen,
            f"duplicate object in the generation manifest: {object_id}",
        )
        seen.add(object_id)

        source = entry.get("source_video")
        _require(
            isinstance(source, Mapping),
            f"{where}.source_video must be an object",
        )
        for field in ("filename", "sha256", "size_bytes"):
            _require(
                source.get(field) is not None,
                f"{where}.source_video.{field} is required",
            )
        filename = str(source["filename"])
        _require(
            Path(filename).name == filename,
            f"{where}.source_video.filename must be a bare name: {filename}",
        )
        video_path = _contained(
            video_dir, filename, f"{where}.source_video.filename"
        )
        _require(
            video_path.is_file(),
            f"source video is missing: {filename}",
        )
        actual_size = video_path.stat().st_size
        _require(
            actual_size == int(source["size_bytes"]),
            f"{object_id}: source video size is {actual_size}, manifest "
            f"declares {source['size_bytes']}",
        )
        actual_sha = _sha256_file(video_path)
        _require(
            actual_sha == str(source["sha256"]),
            f"{object_id}: source video SHA-256 disagrees with the "
            "generation manifest",
        )

        representations = entry.get("representations")
        _require(
            isinstance(representations, Mapping),
            f"{where}.representations must be an object",
        )
        frames_entry = representations.get(SOURCE_REPRESENTATION_ID)
        _require(
            isinstance(frames_entry, Mapping),
            f"{where} has no {SOURCE_REPRESENTATION_ID} representation",
        )
        relative = str(frames_entry.get("path") or "")
        description_path = _contained(
            representation_dir,
            relative,
            f"{where}.representations.{SOURCE_REPRESENTATION_ID}.path",
        )
        _require(
            description_path.is_file(),
            f"{object_id}: {relative} is missing",
        )
        description_bytes = description_path.read_bytes()
        declared_sha = frames_entry.get("sha256")
        if declared_sha is not None:
            _require(
                _sha256_bytes(description_bytes) == str(declared_sha),
                f"{object_id}: {relative} SHA-256 disagrees with the "
                "generation manifest",
            )
        declared_size = frames_entry.get("size_bytes")
        if declared_size is not None:
            _require(
                len(description_bytes) == int(declared_size),
                f"{object_id}: {relative} size disagrees with the manifest",
            )

        try:
            document = json.loads(description_bytes)
        except json.JSONDecodeError as exc:
            raise FrameBundleError(
                f"{object_id}: {relative} is not valid JSON"
            ) from exc
        _require(
            isinstance(document, Mapping),
            f"{object_id}: {relative} must be an object",
        )
        _require(
            document.get("object_id") == object_id,
            f"{object_id}: {relative} names a different object",
        )
        sampling = document.get("sampling")
        _require(
            isinstance(sampling, Mapping),
            f"{object_id}: {relative} has no sampling block",
        )
        # Read the frozen settings; never substitute a module default.
        for field in ("frame_count", "jpeg_max_dimension", "method"):
            _require(
                sampling.get(field) is not None,
                f"{object_id}: sampling.{field} is required and has no "
                "default",
            )
        frame_count = int(sampling["frame_count"])
        max_dimension = int(sampling["jpeg_max_dimension"])
        method = str(sampling["method"])
        _require(
            frame_count == declared_frame_count
            and max_dimension == declared_max_dimension,
            f"{object_id}: frozen sampling settings disagree with the "
            "generation manifest",
        )
        _require(
            method == SAMPLING_METHOD,
            f"{object_id}: unsupported sampling method {method!r}; this "
            f"builder reuses the {SAMPLING_METHOD!r} sampler only",
        )
        duration = document.get("source_duration_seconds")
        _require(
            isinstance(duration, (int, float))
            and not isinstance(duration, bool),
            f"{object_id}: source_duration_seconds is required",
        )
        video_id = document.get("source_video_id")
        _require(
            isinstance(video_id, str) and video_id.strip(),
            f"{object_id}: source_video_id is required",
        )
        _require(
            f"{video_id}.mp4" == filename,
            f"{object_id}: source_video_id {video_id!r} does not match "
            f"filename {filename!r}",
        )
        declared_video_sha = document.get("source_video_sha256")
        if declared_video_sha is not None:
            _require(
                str(declared_video_sha) == actual_sha,
                f"{object_id}: {relative} records a different source video "
                "SHA-256",
            )
        frames = document.get("frames")
        _require(
            isinstance(frames, list) and len(frames) == frame_count,
            f"{object_id}: expected {frame_count} frame descriptions",
        )
        for position, frame in enumerate(frames):
            _require(
                isinstance(frame, Mapping),
                f"{object_id}: frames[{position}] must be an object",
            )
            for field in (
                "frame_index", "timestamp_seconds", "width", "height",
            ):
                _require(
                    frame.get(field) is not None,
                    f"{object_id}: frames[{position}].{field} is required",
                )
        objects.append(FrozenObject(
            object_id=object_id,
            source_video_id=str(video_id),
            video_filename=filename,
            video_size_bytes=actual_size,
            video_sha256=actual_sha,
            video_path=video_path,
            frame_descriptions_relative_path=relative,
            frame_descriptions_sha256=_sha256_bytes(description_bytes),
            frame_count=frame_count,
            jpeg_max_dimension=max_dimension,
            sampling_method=method,
            source_duration_seconds=float(duration),
            frames=tuple(dict(frame) for frame in frames),
        ))
    return objects


def _compare_alignment(
    frozen: FrozenObject,
    sampled: Sequence[SampledImage],
) -> None:
    """Every frozen frame must match the regenerated one exactly."""
    _require(
        len(sampled) == frozen.frame_count,
        f"{frozen.object_id}: resampling produced {len(sampled)} frames, "
        f"frozen metadata declares {frozen.frame_count}",
    )
    for position, (frame, image) in enumerate(zip(frozen.frames, sampled)):
        for label, frozen_value, actual in (
            ("frame_index", int(frame["frame_index"]), image.frame_index),
            ("width", int(frame["width"]), image.width),
            ("height", int(frame["height"]), image.height),
        ):
            _require(
                frozen_value == actual,
                f"{frozen.object_id}: frames[{position}].{label} is "
                f"{actual}, frozen metadata declares {frozen_value}",
            )
        frozen_timestamp = float(frame["timestamp_seconds"])
        _require(
            frozen_timestamp == image.timestamp_seconds,
            f"{frozen.object_id}: frames[{position}].timestamp_seconds is "
            f"{image.timestamp_seconds}, frozen metadata declares "
            f"{frozen_timestamp}",
        )


def _frame_member_name(index: int) -> str:
    return f"{FRAMES_DIRECTORY}/{index:03d}.jpg"


def _deterministic_tar(members: Sequence[tuple[str, bytes]]) -> bytes:
    """Archive members with fully explicit metadata.

    Nothing here is read from the filesystem: mtime, ownership, and mode are
    fixed, names are canonical POSIX, and order is lexicographic. Shelling
    out to ``tar`` would make the bytes depend on the host's tar build.
    """
    ordered = sorted(members, key=lambda item: item[0])
    buffer = io.BytesIO()
    with tarfile.open(
        fileobj=buffer,
        mode="w",
        format=TAR_FORMAT,
    ) as archive:
        for name, payload in ordered:
            info = tarfile.TarInfo(name=name)
            info.size = len(payload)
            info.mtime = TAR_MTIME
            info.mode = TAR_MODE
            info.type = tarfile.REGTYPE
            info.uid = 0
            info.gid = 0
            info.uname = ""
            info.gname = ""
            archive.addfile(info, io.BytesIO(payload))
    return buffer.getvalue()


def _object_manifest(
    frozen: FrozenObject,
    sampled: Sequence[SampledImage],
    *,
    generation_manifest_sha256: str,
    versions: Mapping[str, str | None],
) -> dict[str, Any]:
    frames = []
    for image in sampled:
        payload = image.jpeg_bytes
        frames.append({
            "frame_index": image.frame_index,
            "timestamp_seconds": image.timestamp_seconds,
            "width": image.width,
            "height": image.height,
            "path": _frame_member_name(image.frame_index),
            "jpeg_size_bytes": len(payload),
            "jpeg_sha256": _sha256_bytes(payload),
        })
    return {
        "schema_version": FRAME_BUNDLE_SCHEMA_VERSION,
        "representation_id": REPRESENTATION_ID,
        "object_id": frozen.object_id,
        "source_video_id": frozen.source_video_id,
        "source_video_filename": frozen.video_filename,
        "source_video_size_bytes": frozen.video_size_bytes,
        "source_video_sha256": frozen.video_sha256,
        "source_duration_seconds": frozen.source_duration_seconds,
        "sampling": {
            "method": frozen.sampling_method,
            "frame_count": frozen.frame_count,
            "jpeg_max_dimension": frozen.jpeg_max_dimension,
            "jpeg_quality": JPEG_QUALITY,
            "jpeg_optimize": JPEG_OPTIMIZE,
        },
        "source_frame_descriptions": {
            "representation_id": SOURCE_REPRESENTATION_ID,
            "path": frozen.frame_descriptions_relative_path,
            "sha256": frozen.frame_descriptions_sha256,
        },
        "generation_manifest_sha256": generation_manifest_sha256,
        "frames": frames,
        "frame_count": len(frames),
        "total_jpeg_bytes": sum(
            frame["jpeg_size_bytes"] for frame in frames
        ),
        "software_versions": dict(sorted(versions.items())),
        "historical_visual_bytes_retained": False,
        "sampling_alignment_statement": _ALIGNMENT_STATEMENT,
        "claims_byte_identity_with_historical_visual_input": False,
        "credentials_recorded": False,
        "llm_called": False,
        "network_calls_performed": False,
    }


def build_frame_bundles(
    *,
    video_dir: str | Path,
    representation_dir: str | Path,
    output_dir: str | Path,
    generation_manifest: str | Path | None = None,
    sampler: FrameSampler | None = None,
    object_ids: Sequence[str] | None = None,
) -> dict[str, Any]:
    """Build one deterministic frame bundle per declared object."""
    videos = Path(video_dir).resolve()
    representations = Path(representation_dir).resolve()
    target = Path(output_dir).resolve()
    _require(videos.is_dir(), f"video directory does not exist: {videos}")
    _require(
        representations.is_dir(),
        f"representation directory does not exist: {representations}",
    )
    _require(
        not target.exists(),
        f"output directory already exists: {target}",
    )
    decode = sampler if sampler is not None else sample_video

    manifest_path, manifest, manifest_bytes = _load_generation_manifest(
        representations, generation_manifest
    )
    generation_manifest_sha256 = _sha256_bytes(manifest_bytes)
    frozen_objects = _validate_objects(
        manifest,
        representation_dir=representations,
        video_dir=videos,
    )
    if object_ids is not None:
        wanted = set(object_ids)
        unknown = sorted(
            wanted - {item.object_id for item in frozen_objects}
        )
        _require(
            not unknown,
            "requested objects are not in the generation manifest: "
            + ", ".join(unknown),
        )
        frozen_objects = [
            item for item in frozen_objects if item.object_id in wanted
        ]
        _require(frozen_objects, "no objects selected")

    versions = _software_versions()
    staging_parent = target.parent
    staging_parent.mkdir(parents=True, exist_ok=True)
    staging_root = Path(mkdtemp(
        prefix=".pathfinder-frame-bundle-",
        dir=staging_parent,
    ))
    staging = staging_root / "bundle"
    try:
        staging.mkdir()
        entries: list[dict[str, Any]] = []
        total_frames = 0
        total_jpeg_bytes = 0
        total_tar_bytes = 0
        for frozen in sorted(
            frozen_objects, key=lambda item: item.object_id
        ):
            sampled, _duration = decode(
                frozen.video_path,
                frame_count=frozen.frame_count,
                jpeg_max_dimension=frozen.jpeg_max_dimension,
            )
            _compare_alignment(frozen, sampled)

            object_dir = staging / frozen.object_id
            frames_dir = object_dir / FRAMES_DIRECTORY
            frames_dir.mkdir(parents=True)
            members: list[tuple[str, bytes]] = []
            for image in sampled:
                member = _frame_member_name(image.frame_index)
                # The exact bytes the sampler returned, unmodified.
                (object_dir / member).write_bytes(image.jpeg_bytes)
                members.append((member, image.jpeg_bytes))

            document = _object_manifest(
                frozen,
                sampled,
                generation_manifest_sha256=generation_manifest_sha256,
                versions=versions,
            )
            object_manifest_bytes = _canonical_json(document)
            # One byte string, written externally and embedded, so the two
            # copies cannot drift.
            (object_dir / OBJECT_MANIFEST_NAME).write_bytes(
                object_manifest_bytes
            )
            members.append((OBJECT_MANIFEST_NAME, object_manifest_bytes))

            archive = _deterministic_tar(members)
            (object_dir / BUNDLE_NAME).write_bytes(archive)

            object_jpeg_bytes = int(document["total_jpeg_bytes"])
            total_frames += len(sampled)
            total_jpeg_bytes += object_jpeg_bytes
            total_tar_bytes += len(archive)
            entries.append({
                "object_id": frozen.object_id,
                "source_video_id": frozen.source_video_id,
                "object_manifest_path": (
                    f"{frozen.object_id}/{OBJECT_MANIFEST_NAME}"
                ),
                "object_manifest_size_bytes": len(object_manifest_bytes),
                "object_manifest_sha256": _sha256_bytes(
                    object_manifest_bytes
                ),
                "bundle_path": f"{frozen.object_id}/{BUNDLE_NAME}",
                "bundle_size_bytes": len(archive),
                "bundle_sha256": _sha256_bytes(archive),
                "frame_count": len(sampled),
                "total_jpeg_bytes": object_jpeg_bytes,
            })

        generation = {
            "schema_version": FRAME_BUNDLE_GENERATION_SCHEMA_VERSION,
            "representation_id": REPRESENTATION_ID,
            "source_generation_manifest": {
                "filename": manifest_path.name,
                "sha256": generation_manifest_sha256,
                "schema_version": manifest.get("schema_version"),
            },
            "input_video_sha256": {
                item.video_filename: item.video_sha256
                for item in sorted(
                    frozen_objects, key=lambda x: x.video_filename
                )
            },
            "object_count": len(entries),
            "total_frame_count": total_frames,
            "total_jpeg_bytes": total_jpeg_bytes,
            "total_tar_bytes": total_tar_bytes,
            "sampling": {
                "method": SAMPLING_METHOD,
                "frame_count": frozen_objects[0].frame_count,
                "jpeg_max_dimension": (
                    frozen_objects[0].jpeg_max_dimension
                ),
                "jpeg_quality": JPEG_QUALITY,
                "jpeg_optimize": JPEG_OPTIMIZE,
            },
            "tar_determinism": {
                "format": "USTAR",
                "mtime": TAR_MTIME,
                "mode": TAR_MODE,
                "uid": 0,
                "gid": 0,
                "uname": "",
                "gname": "",
                "member_order": "lexicographic",
            },
            "software_versions": dict(sorted(versions.items())),
            "objects": entries,
            "historical_visual_bytes_retained": False,
            "sampling_alignment_statement": _ALIGNMENT_STATEMENT,
            "claims_byte_identity_with_historical_visual_input": False,
            "replaces_sampled_frames_representation": False,
            "credentials_recorded": False,
            "llm_called": False,
            "network_calls_performed": False,
            "deployment_mutations_performed": False,
        }
        (staging / GENERATION_MANIFEST_NAME).write_bytes(
            _canonical_json(generation)
        )

        checksums = _checksum_document(staging)
        (staging / CHECKSUM_NAME).write_text(
            checksums, encoding="utf-8", newline="\n"
        )
        _verify_checksums(staging)

        _require(
            not target.exists(),
            f"output directory already exists: {target}",
        )
        staging.rename(target)
    except BaseException:
        # Inputs are immutable and generation is cheap, so a failed staging
        # tree is discarded rather than left to be mistaken for a result.
        shutil.rmtree(staging_root, ignore_errors=True)
        raise
    else:
        shutil.rmtree(staging_root, ignore_errors=True)

    return {
        "status": "COMPLETE",
        "representation_id": REPRESENTATION_ID,
        "object_count": len(entries),
        "total_frame_count": total_frames,
        "total_jpeg_bytes": total_jpeg_bytes,
        "total_tar_bytes": total_tar_bytes,
        "generation_manifest_sha256": generation_manifest_sha256,
        "historical_visual_bytes_retained": False,
        "claims_byte_identity_with_historical_visual_input": False,
        "credentials_recorded": False,
        "llm_called": False,
        "network_calls_performed": False,
        "console_only_paths": {"output_dir": str(target)},
    }


def _checksum_document(root: Path) -> str:
    lines = []
    for path in sorted(
        (p for p in root.rglob("*") if p.is_file()),
        key=lambda p: p.relative_to(root).as_posix(),
    ):
        relative = path.relative_to(root).as_posix()
        if relative == CHECKSUM_NAME:
            continue
        lines.append(f"{_sha256_file(path)}  {relative}\n")
    return "".join(lines)


def _verify_checksums(root: Path) -> None:
    path = root / CHECKSUM_NAME
    _require(path.is_file(), "SHA256SUMS was not written")
    for line in path.read_text(encoding="utf-8").splitlines():
        if not line.strip():
            continue
        digest, name = line.split("  ", 1)
        target = root / name
        _require(target.is_file(), f"SHA256SUMS references {name}")
        _require(
            _sha256_file(target) == digest,
            f"SHA256SUMS mismatch for {name}",
        )
